version: "3"

services:
  mongo:
    container_name: mongodb
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: clean-node-api
    build: .
    image: clean-node-api
    working_dir: /usr/src/clean-node-api
    restart: always
    command: npm start
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
      - ./package-lock.json:/usr/src/clean-node-api/package-lock.json
    ports:
      - "5050:5050"
    links:
      - mongo